import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Navbar from '@/app/component/Navbar'

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400','600', '700'],
})

export const metadata = {
  title: 'Next JS by Coomar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='max-w-4xl mx-auto px-5'>
          <Navbar />
          {children}
        </div>
        </body>
    </html>
  )
}
